on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: carlthome/workflows/.github/workflows/nix.yaml@main
    with:
      cachix-cache: nix-jax-mnist
    secrets:
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
